services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: apptodolist
    restart: always
    ports:
      - "8080:8080"
    command: [ "uvicorn", "--reload", "--host", "0.0.0.0", "--port", "8080", "apptodolist.web:app" ]
    environment:
      ENV: "dev"
    develop:
      watch:
        - action: sync
          path: src
          target: /src/src
        - action: rebuild
          path: Dockerfile
        - action: rebuild
          path: pyproject.toml
        - action: rebuild
          path: uv.lock
        - action: rebuild
          path: docker-compose.yml
